import { mkdtemp, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { describe, expect, it, vi } from 'vitest'
import { ADAPTIVE_POLICIES, ADAPTIVE_STATES, runAdaptiveSemanticBatch, summarizeAdaptiveBatch } from './adaptiveSemanticBatchCore.mjs'

const validOutput = (short = false) => { const evidence = () => ({ rationale: 'A sufficiently detailed factual rationale.', sourceRefs: ['tmdb-overview'], grounding: { mode: 'direct', cues: [{ sourceRef: 'tmdb-overview', cue: short ? 'short' : 'a sufficiently long factual cue' }] } }); return { classification: { moods: ['thoughtful'], situations: ['alone'], filterLanguages: ['English'], pace: 'medium', emotionalWeight: 'moderate', attentionDemand: 'engaged', discoveryStyle: 'different' }, evidence: { moods: { thoughtful: evidence() }, situations: { alone: evidence() }, pace: evidence(), emotionalWeight: evidence(), attentionDemand: evidence(), discoveryStyle: evidence() }, boundaryFlags: [] } }
const response = (output, total = 30) => ({ ok: true, status: 200, headers: { get: () => null }, json: async () => ({ choices: [{ finish_reason: 'stop', message: { content: JSON.stringify(output) } }], usage: { prompt_tokens: 10, completion_tokens: 20, total_tokens: total, completion_tokens_details: { reasoning_tokens: 7 } } }) })
async function fixture(existing = null, imported = false) { const root = await mkdtemp(join(tmpdir(), 'semantic-low-policy-')); const candidate = { candidateId: 'fresh', tmdbId: 1, evidencePacketHash: 'sha256:fresh' }; const importedCandidate = { candidateId: 'imported', tmdbId: 2, evidencePacketHash: 'sha256:imported' }; return { root, context: { runtime: { runRoot: root, manifestPath: join(root, 'manifest.json'), responseRoot: join(root, 'responses'), outputRoot: join(root, 'artifacts'), cacheRoot: join(root, 'cache'), lockPath: join(root, 'RUN_LOCK') }, identity: { runId: 'semantic-200-fixture', providerId: 'moonshot-kimi-api', modelId: 'kimi-for-coding', outputMode: 'json_schema', semanticOutputSchemaVersion: 'semantic-output.v2', promptVersion: 'semantic-classifier.v3', semanticPolicyVersion: ADAPTIVE_POLICIES.lowHighMax.version }, candidates: imported ? [importedCandidate, candidate] : [candidate], importedStates: imported ? new Map([[importedCandidate.candidateId, { ...importedCandidate, status: ADAPTIVE_STATES.imported, semanticAttempts: { low: 0, high: 0, max: 0 }, usage: { low: {}, high: {}, max: {} }, httpRequests: 0, events: [] }]]) : new Map(), packets: new Map([[candidate.candidateId, { schemaVersion: 'evidence-packet.v1', ...candidate, inputHash: candidate.evidencePacketHash, sourceProvenance: [{ source: 'tmdb-overview' }], facts: {} }]]), prompt: 'fixture prompt', manifest: existing } } }
const efforts = (fetchImpl) => fetchImpl.mock.calls.map(([, init]) => JSON.parse(init.body).reasoning_effort)

describe('Low→High→Max adaptive semantic policy', () => {
  it('starts fresh Semantic-N work at Low and a valid Low response is terminal', async () => { const { root, context } = await fixture(); const fetchImpl = vi.fn().mockResolvedValue(response(validOutput())); try { const { manifest } = await runAdaptiveSemanticBatch({ context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(efforts(fetchImpl)).toEqual(['low']); expect(manifest.states.fresh).toMatchObject({ status: ADAPTIVE_STATES.lowValid, semanticAttempts: { low: 1, high: 0, max: 0 }, validatedEffort: 'low' }) } finally { await rm(root, { recursive: true, force: true }) } })
  it('escalates Low semantic-invalid to High, but never on a Low provider failure', async () => { const first = await fixture(); const semanticFetch = vi.fn().mockResolvedValueOnce(response(validOutput(true), 25)).mockResolvedValueOnce(response(validOutput(), 30)); try { const { manifest } = await runAdaptiveSemanticBatch({ context: first.context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl: semanticFetch, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(efforts(semanticFetch)).toEqual(['low', 'high']); expect(manifest.states.fresh).toMatchObject({ status: ADAPTIVE_STATES.highValid, lowSemanticFailure: expect.any(Object), semanticAttempts: { low: 1, high: 1, max: 0 } }) } finally { await rm(first.root, { recursive: true, force: true }) }
    const second = await fixture(); const providerFetch = vi.fn().mockResolvedValue({ ok: false, status: 401, headers: { get: () => null }, text: async () => '' }); try { const { manifest } = await runAdaptiveSemanticBatch({ context: second.context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl: providerFetch, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(efforts(providerFetch)).toEqual(['low']); expect(manifest.states.fresh.status).toBe(ADAPTIVE_STATES.terminalProviderFailure) } finally { await rm(second.root, { recursive: true, force: true }) } })
  it('does not escalate a High provider failure to Max', async () => { const { root, context } = await fixture(); const fetchImpl = vi.fn().mockResolvedValueOnce(response(validOutput(true))).mockResolvedValueOnce({ ok: false, status: 503, headers: { get: () => null }, text: async () => '' }); try { const { manifest } = await runAdaptiveSemanticBatch({ context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl, maxFreshCandidates: 1, maxHttpRequests: 2, maxTransportAttempts: 1 }); expect(efforts(fetchImpl)).toEqual(['low', 'high']); expect(manifest.states.fresh).toMatchObject({ status: ADAPTIVE_STATES.retryableProviderFailure, failedEffort: 'high', semanticAttempts: { low: 1, high: 1, max: 0 } }) } finally { await rm(root, { recursive: true, force: true }) } })
  it('escalates High semantic-invalid to Max and makes Max semantic-invalid terminal', async () => { const recovered = await fixture(); const fetchImpl = vi.fn().mockResolvedValueOnce(response(validOutput(true))).mockResolvedValueOnce(response(validOutput(true))).mockResolvedValueOnce(response(validOutput())); try { const { manifest } = await runAdaptiveSemanticBatch({ context: recovered.context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(efforts(fetchImpl)).toEqual(['low', 'high', 'max']); expect(manifest.states.fresh.status).toBe(ADAPTIVE_STATES.maxValid) } finally { await rm(recovered.root, { recursive: true, force: true }) }
    const failed = await fixture(); const allInvalid = vi.fn().mockResolvedValue(response(validOutput(true))); try { const { manifest } = await runAdaptiveSemanticBatch({ context: failed.context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl: allInvalid, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(allInvalid).toHaveBeenCalledTimes(3); expect(manifest.states.fresh.status).toBe(ADAPTIVE_STATES.terminalSemanticFailure) } finally { await rm(failed.root, { recursive: true, force: true }) } })
  it.each(['low', 'high', 'max'])('makes an unknown %s transport outcome uncertain without moving tiers', async (effort) => { const stateByEffort = { low: ADAPTIVE_STATES.pendingLow, high: ADAPTIVE_STATES.lowSemanticFailedHighPending, max: ADAPTIVE_STATES.highSemanticFailedMaxPending }; const attempts = { low: effort === 'low' ? 0 : 1, high: effort === 'max' ? 1 : 0, max: 0 }; const existing = { schemaVersion: 'adaptive-semantic-batch.v1', runId: 'semantic-200-fixture', providerId: 'moonshot-kimi-api', modelId: 'kimi-for-coding', outputMode: 'json_schema', semanticOutputSchemaVersion: 'semantic-output.v2', promptVersion: 'semantic-classifier.v3', semanticPolicyVersion: ADAPTIVE_POLICIES.lowHighMax.version, currentRunHttpRequests: 0, states: { fresh: { candidateId: 'fresh', tmdbId: 1, evidencePacketHash: 'sha256:fresh', status: stateByEffort[effort], semanticAttempts: attempts, usage: { low: {}, high: {}, max: {} }, httpRequests: 0, events: [] } } }; const { root, context } = await fixture(existing); const fetchImpl = vi.fn().mockRejectedValue(new Error('unknown')); try { const { manifest } = await runAdaptiveSemanticBatch({ context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(efforts(fetchImpl)).toEqual([effort]); expect(manifest.states.fresh.status).toBe(ADAPTIVE_STATES.uncertain) } finally { await rm(root, { recursive: true, force: true }) } })
  it('does not dispatch imported, valid, or uncertain records on resume', async () => { const statuses = [ADAPTIVE_STATES.imported, ADAPTIVE_STATES.lowValid, ADAPTIVE_STATES.uncertain]; for (const status of statuses) { const existing = { schemaVersion: 'adaptive-semantic-batch.v1', currentRunHttpRequests: 0, states: { fresh: { candidateId: 'fresh', tmdbId: 1, evidencePacketHash: 'sha256:fresh', status, semanticAttempts: { low: status === ADAPTIVE_STATES.imported ? 0 : 1, high: 0, max: 0 }, usage: { low: {}, high: {}, max: {} }, events: [] } } }; const { root, context } = await fixture(existing); const fetchImpl = vi.fn(); try { await runAdaptiveSemanticBatch({ context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl, maxFreshCandidates: 1, maxHttpRequests: 3 }); expect(fetchImpl).not.toHaveBeenCalled() } finally { await rm(root, { recursive: true, force: true }) } } })
  it('accounts Low/High/Max separately, excludes imports, and obeys the shared HTTP cap', async () => { const { root, context } = await fixture(null, true); const fetchImpl = vi.fn().mockResolvedValue(response(validOutput(true), 30)); try { const { manifest } = await runAdaptiveSemanticBatch({ context, policy: ADAPTIVE_POLICIES.lowHighMax, env: { KIMI_API_KEY: 'x' }, fetchImpl, maxFreshCandidates: 1, maxHttpRequests: 2 }); expect(fetchImpl).toHaveBeenCalledTimes(2); expect(manifest.states.fresh.status).toBe(ADAPTIVE_STATES.highSemanticFailedMaxPending); expect(summarizeAdaptiveBatch(manifest)).toMatchObject({ importedValid: 1, pending: 1, lowAttempts: 1, highAttempts: 1, maxAttempts: 0, tokenAccountingCurrentRun: { low: { total_tokens: 30 }, high: { total_tokens: 30 }, max: { total_tokens: 0 }, combined: { total_tokens: 60 } } }) } finally { await rm(root, { recursive: true, force: true }) } })
})
