import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import taxonomy from '../config/taxonomyVersion.json' with { type: 'json' }
import anchors from '../calibration/anchors.json' with { type: 'json' }
import boundaryCases from '../calibration/boundaryCases.json' with { type: 'json' }
import { createKimiProvider, KIMI_PROVIDER_ID } from '../adapters/kimiProvider.ts'
import { stableHash } from '../adapters/tmdbProvider.ts'
import { CLOSURE_PATH, verifyAndDeriveAdaptiveScale50Closure } from './closeKimiAdaptiveScale50.mjs'
import { ADAPTIVE_STATES, fileExists, readJson, runAdaptiveSemanticBatch, summarizeAdaptiveBatch } from './adaptiveSemanticBatchCore.mjs'

export const RUN_ID = 'kimi-k28-adaptive-semantic-100-v1'
export const AUTHORIZATION_FLAG = '--execute-authorized-semantic-100'
export const SOURCE_BATCH_ID = 'expansion-100-v1'
export const SCALE_50_RUN_ID = 'kimi-k28-adaptive-scale-50-v1'
export const SCHEMA_HASH = 'sha256:a5bacc030ad25d46a01856f6e49d6d041809683e82d2469d23ac9eae412866fc'
export const SCALE50_CLOSURE_RAW_SHA256 = 'sha256:eccbd9cf767e67887199e72f28f256a55ba3142c997eff273748bb6d4e51a507'
const sha256 = (bytes) => `sha256:${createHash('sha256').update(bytes).digest('hex')}`
const required = ['runId', 'providerId', 'modelId', 'outputMode', 'semanticOutputSchemaVersion', 'semanticOutputSchemaHash', 'promptVersion', 'promptContentHash', 'taxonomyHash', 'calibrationAnchorsHash', 'boundaryCasesHash', 'highMaxPolicyVersion', 'highProviderConfiguration', 'maxProviderConfiguration']
export class Semantic100Error extends Error { constructor(message, { code = 'SEMANTIC_100_ERROR', details = {} } = {}) { super(message); this.name = 'Semantic100Error'; this.code = code; this.details = details } }
const fail = (message, code, details = {}) => { throw new Semantic100Error(message, { code, details }) }
const paths = (pipelineRoot) => { const runRoot = resolve(pipelineRoot, 'generated/semantic/batches', RUN_ID); return { runRoot, manifestPath: resolve(runRoot, 'manifest.json'), responseRoot: resolve(runRoot, 'responses'), outputRoot: resolve(runRoot, 'artifacts'), cacheRoot: resolve(pipelineRoot, 'cache/semantic/batches', RUN_ID), lockPath: resolve(runRoot, 'RUN_LOCK') } }
const integerFlag = (argv, name) => { const index = argv.indexOf(name); if (index < 0 || !/^(0|[1-9]\d*)$/.test(argv[index + 1] ?? '')) fail(`Missing or invalid ${name}.`, 'INVALID_INVOCATION_BUDGET'); return Number(argv[index + 1]) }
const optionalIntegerFlag = (argv, name) => argv.includes(name) ? integerFlag(argv, name) : null

export async function buildSemantic100Preflight({ pipelineRoot = resolve('catalogue-pipeline'), root = process.cwd(), readJsonFile = readJson, readTextFile = readFile, readRawFile = readFile, fileExists: exists = fileExists, verifyScale50Closure = verifyAndDeriveAdaptiveScale50Closure } = {}) {
  const sourceRoot = resolve(pipelineRoot, 'generated/catalogue-expansion', SOURCE_BATCH_ID); const scaleRoot = resolve(pipelineRoot, 'generated/catalogue-expansion/scale-50-v1')
  const [expansion, scale50, prompt, closureRaw] = await Promise.all([readJsonFile(resolve(sourceRoot, 'candidate-manifest.json')), readJsonFile(resolve(scaleRoot, 'candidate-manifest.json')), readTextFile(resolve(pipelineRoot, 'prompts/semantic-classifier.v3.md'), 'utf8'), readRawFile(resolve(root, CLOSURE_PATH))])
  if (sha256(closureRaw) !== SCALE50_CLOSURE_RAW_SHA256) fail('Closed Scale-50 closure raw hash drift.', 'SCALE50_CLOSURE_HASH_MISMATCH')
  const closure = await verifyScale50Closure({ root }); if (closure.status !== 'CLOSED' || closure.outcome?.completedValid !== 50 || closure.identity?.runId !== SCALE_50_RUN_ID) fail('Closed Scale-50 closure verification failed.', 'SCALE50_CLOSURE_INVALID')
  if (expansion?.batchId !== SOURCE_BATCH_ID || expansion?.candidates?.length !== 100 || new Set(expansion.candidates.map((candidate) => candidate.candidateId)).size !== 100) fail('Expansion-100 identity or uniqueness mismatch.', 'EXPANSION_100_MISMATCH')
  if (scale50?.candidates?.length !== 50 || !scale50.scaleManifestHash) fail('Scale-50 manifest mismatch.', 'SCALE50_MANIFEST_MISMATCH')
  const placeholder = { KIMI_API_KEY: 'offline-preflight-placeholder' }; const neverFetch = async () => fail('Preflight must never dispatch HTTP.', 'PREFLIGHT_HTTP_FORBIDDEN'); const high = createKimiProvider({ modelId: 'kimi-for-coding', reasoningEffort: 'high', outputMode: 'json_schema', semanticOutputSchemaVersion: 'semantic-output.v2', env: placeholder, fetchImpl: neverFetch }); const max = createKimiProvider({ modelId: 'kimi-for-coding', reasoningEffort: 'max', outputMode: 'json_schema', semanticOutputSchemaVersion: 'semantic-output.v2', env: placeholder, fetchImpl: neverFetch })
  if (high.metadata.outputAffectingConfiguration.semanticOutputSchemaHash !== SCHEMA_HASH || max.metadata.outputAffectingConfiguration.semanticOutputSchemaHash !== SCHEMA_HASH) fail('Structured schema identity drift.', 'SCHEMA_HASH_MISMATCH')
  const identity = { runId: RUN_ID, sourceBatchId: SOURCE_BATCH_ID, sourceCandidateManifestHash: expansion.candidateManifestHash, importedScale50ManifestHash: scale50.scaleManifestHash, importedScale50ClosureRawSha256: SCALE50_CLOSURE_RAW_SHA256, providerId: KIMI_PROVIDER_ID, modelId: 'kimi-for-coding', outputMode: 'json_schema', semanticOutputSchemaVersion: 'semantic-output.v2', semanticOutputSchemaHash: SCHEMA_HASH, promptVersion: 'semantic-classifier.v3', promptContentHash: `sha256:${stableHash(prompt)}`, taxonomyHash: `sha256:${stableHash(taxonomy)}`, calibrationAnchorsHash: `sha256:${stableHash(anchors)}`, boundaryCasesHash: `sha256:${stableHash(boundaryCases)}`, highMaxPolicyVersion: 'kimi-k28-high-then-max-on-semantic-failure.v1', highProviderConfiguration: high.metadata.outputAffectingConfiguration, maxProviderConfiguration: max.metadata.outputAffectingConfiguration }
  const runManifest = await readJsonFile(resolve(pipelineRoot, 'generated/semantic/batches', SCALE_50_RUN_ID, 'manifest.json')); for (const key of required.filter((key) => key !== 'runId')) if (stableHash(runManifest[key]) !== stableHash({ ...identity, runId: SCALE_50_RUN_ID }[key])) fail(`Scale-50 semantic identity drift: ${key}.`, 'SCALE50_SEMANTIC_IDENTITY_MISMATCH', { key })
  const packets = new Map(); for (const candidate of expansion.candidates) { const packet = await readJsonFile(resolve(sourceRoot, 'evidence-packets', `${candidate.candidateId}.json`)); if (packet?.candidateId !== candidate.candidateId || packet?.tmdbId !== candidate.tmdbId || typeof packet?.inputHash !== 'string') fail('Expansion evidence packet drift.', 'EVIDENCE_PACKET_IDENTITY_MISMATCH', { candidateId: candidate.candidateId }); packets.set(candidate.candidateId, packet) }
  const candidates = expansion.candidates.map((candidate) => ({ ...candidate, evidencePacketHash: packets.get(candidate.candidateId).inputHash })); const expansionById = new Map(candidates.map((candidate) => [candidate.candidateId, candidate])); const importedStates = new Map()
  for (const selected of scale50.candidates) {
    const candidate = expansionById.get(selected.candidateId); const prior = runManifest.states?.[selected.candidateId]
    if (!candidate || candidate.tmdbId !== selected.tmdbId || candidate.evidencePacketHash !== selected.evidencePacketHash || !prior || ![ADAPTIVE_STATES.highValid, ADAPTIVE_STATES.maxValid].includes(prior.status)) fail('Scale-50 imported candidate identity/state mismatch.', 'IMPORT_IDENTITY_MISMATCH', { candidateId: selected.candidateId })
    const raw = await readRawFile(prior.artifactPath); const artifact = JSON.parse(raw)
    if (artifact.outputHash !== prior.artifactHash || artifact.movie?.candidateId !== candidate.candidateId || artifact.movie?.tmdbId !== candidate.tmdbId || artifact.evidencePacketHash !== candidate.evidencePacketHash || artifact.modelProvider !== identity.providerId || artifact.modelId !== identity.modelId || artifact.promptVersion !== identity.promptVersion || artifact.schemaVersion !== identity.semanticOutputSchemaVersion || artifact.providerConfiguration?.semanticOutputSchemaHash !== identity.semanticOutputSchemaHash || artifact.providerConfiguration?.reasoningEffort !== prior.validatedEffort) fail('Imported Scale-50 artifact drift.', 'IMPORT_ARTIFACT_DRIFT', { candidateId: candidate.candidateId })
    importedStates.set(candidate.candidateId, { candidateId: candidate.candidateId, tmdbId: candidate.tmdbId, evidencePacketHash: candidate.evidencePacketHash, status: ADAPTIVE_STATES.imported, semanticAttempts: { high: 0, max: 0 }, usage: { high: {}, max: {} }, httpRequests: 0, events: [{ type: 'IMPORTED_VALID_REFERENCE', sourceRunId: SCALE_50_RUN_ID, artifactHash: prior.artifactHash }], lifetimeProvenance: { sourceRunId: SCALE_50_RUN_ID, candidateId: candidate.candidateId, tmdbId: candidate.tmdbId, evidencePacketHash: candidate.evidencePacketHash, artifactHash: prior.artifactHash, artifactRawSha256: sha256(raw), validatedEffort: prior.validatedEffort, providerId: artifact.modelProvider, modelId: artifact.modelId, promptVersion: artifact.promptVersion, promptContentHash: identity.promptContentHash, schemaVersion: artifact.schemaVersion, schemaHash: artifact.providerConfiguration.semanticOutputSchemaHash, taxonomyHash: identity.taxonomyHash, calibrationAnchorsHash: artifact.calibration?.anchorsHash, boundaryCasesHash: artifact.calibration?.boundaryCasesHash, artifactPath: prior.artifactPath } })
  }
  if (importedStates.size !== 50) fail('Semantic-100 requires exactly 50 Scale-50 imports.', 'IMPORT_COUNT_MISMATCH')
  const cohortHash = `sha256:${stableHash(candidates.map((candidate) => ({ candidateId: candidate.candidateId, tmdbId: candidate.tmdbId, evidencePacketHash: candidate.evidencePacketHash, disposition: importedStates.has(candidate.candidateId) ? 'IMPORTED_VALID' : 'PENDING_HIGH', importArtifactHash: importedStates.get(candidate.candidateId)?.lifetimeProvenance.artifactHash ?? null })))}`
  const runtime = paths(pipelineRoot); let manifest = null; if (await exists(runtime.manifestPath)) { manifest = await readJsonFile(runtime.manifestPath); for (const key of Object.keys(identity)) if (stableHash(manifest[key]) !== stableHash(identity[key])) fail(`Semantic-100 resume identity drift: ${key}.`, 'RUN_IDENTITY_MISMATCH', { key }) }
  const preflight = { ...identity, cohortHash, candidateCount: 100, importedValid: importedStates.size, pendingFresh: candidates.length - importedStates.size, currentRunHttpRequests: manifest?.currentRunHttpRequests ?? 0, generatedValidThisRun: manifest ? summarizeAdaptiveBatch(manifest).generatedValidThisRun : 0, executionAuthorized: false }
  return { preflight, identity: { ...identity, cohortHash }, candidates, importedStates, packets, prompt, runtime, manifest }
}

export async function runAdaptiveSemantic100(options = {}) { const context = await buildSemantic100Preflight(options); return { preflight: context.preflight, ...(await runAdaptiveSemanticBatch({ context, ...options })) } }
export async function launchAdaptiveSemantic100(argv = process.argv.slice(2), options = {}) { const context = await buildSemantic100Preflight(options); const requestedInvocationCap = { maxFreshCandidates: optionalIntegerFlag(argv, '--max-fresh-candidates'), maxHttpRequests: optionalIntegerFlag(argv, '--max-http-requests') }; if (!argv.includes(AUTHORIZATION_FLAG)) return { executionAuthorized: false, preflight: { ...context.preflight, requestedInvocationCap } }; return { executionAuthorized: true, ...(await runAdaptiveSemanticBatch({ context, ...options, maxFreshCandidates: integerFlag(argv, '--max-fresh-candidates'), maxHttpRequests: integerFlag(argv, '--max-http-requests') })) } }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) launchAdaptiveSemantic100().then((result) => console.log(JSON.stringify(result, null, 2))).catch((error) => { console.error(`${error.message} [${error.code ?? 'ERROR'}]`); process.exitCode = 1 })
