import { readFile } from 'node:fs/promises'
import { describe, expect, it, vi } from 'vitest'
import { ADAPTIVE_POLICIES, ADAPTIVE_STATES } from './adaptiveSemanticBatchCore.mjs'
import { buildSemanticNPreflight } from './runKimiAdaptiveSemanticN.mjs'

async function fixture({ identityDrift = false, artifactDrift = false } = {}) {
  const real = JSON.parse(await readFile('catalogue-pipeline/generated/semantic/batches/kimi-k28-adaptive-semantic-100-v1/manifest.json', 'utf8')); const first = Object.values(real.states).find((state) => state.status === ADAPTIVE_STATES.highValid); const template = JSON.parse(await readFile(first.artifactPath, 'utf8')); const prompt = await readFile('catalogue-pipeline/prompts/semantic-classifier.v3.md', 'utf8')
  const importedCandidates = []; const newCandidates = []; const states = {}; const artifacts = new Map()
  for (let i = 0; i < 100; i++) { const candidateId = `old-${i}`; const evidencePacketHash = `sha256:e-old-${i}`; const artifactHash = `sha256:a-${i}`; const artifactPath = `/artifacts/${candidateId}.json`; importedCandidates.push({ candidateId, tmdbId: i + 1, evidencePacketHash, disposition: 'IMPORTED_VALID', priorArtifactHash: artifactHash }); states[candidateId] = { candidateId, tmdbId: i + 1, evidencePacketHash, status: ADAPTIVE_STATES.highValid, artifactPath, artifactHash, validatedEffort: 'high' }; artifacts.set(artifactPath, { ...template, outputHash: artifactDrift && i === 0 ? 'sha256:drift' : artifactHash, movie: { candidateId, tmdbId: i + 1 }, evidencePacketHash, providerConfiguration: { ...template.providerConfiguration, reasoningEffort: 'high' } }) }
  for (let i = 0; i < 100; i++) newCandidates.push({ candidateId: `new-${i}`, tmdbId: 1001 + i, evidencePacketHash: `sha256:e-new-${i}`, disposition: 'PENDING_LOW' })
  const cohort = { cohortId: 'kimi-k28-adaptive-semantic-200-v1', priorRunId: 'kimi-k28-adaptive-semantic-100-v1', targetCount: 200, importedCount: 100, newCount: 100, totalCandidates: 200, cohortHash: 'sha256:cohort', importedCandidates, newCandidates }
  const prior = { ...Object.fromEntries(['providerId', 'modelId', 'outputMode', 'semanticOutputSchemaVersion', 'semanticOutputSchemaHash', 'promptVersion', 'promptContentHash', 'taxonomyHash', 'calibrationAnchorsHash', 'boundaryCasesHash', 'highMaxPolicyVersion', 'highProviderConfiguration', 'maxProviderConfiguration'].map((key) => [key, real[key]])), promptContentHash: identityDrift ? 'sha256:drift' : real.promptContentHash, runId: cohort.priorRunId, states }
  const readJsonFile = vi.fn(async (path) => { if (path.endsWith('/cohort-manifest.json')) return cohort; if (path.endsWith(`/${cohort.priorRunId}/manifest.json`)) return prior; const fresh = newCandidates.find((candidate) => path.endsWith(`/${candidate.candidateId}.json`)); if (fresh) return { schemaVersion: 'evidence-packet.v1', candidateId: fresh.candidateId, tmdbId: fresh.tmdbId, inputHash: fresh.evidencePacketHash }; throw new Error(`unexpected ${path}`) })
  const readRawFile = vi.fn(async (path) => path.endsWith('semantic-classifier.v3.md') ? prompt : Buffer.from(JSON.stringify(artifacts.get(path))))
  return { readJsonFile, readRawFile, exists: async (path) => !(path.endsWith('/manifest.json') && path.includes('semantic-200-v1')) }
}

describe('Semantic-N Low-first preflight', () => {
  it('imports a historical High→Max checkpoint while binding fresh work to Low→High→Max', async () => { const options = await fixture(); const context = await buildSemanticNPreflight({ target: 200, pipelineRoot: '/pipeline', ...options }); expect(context.identity).toMatchObject({ semanticPolicyVersion: ADAPTIVE_POLICIES.lowHighMax.version, lowProviderConfiguration: { reasoningEffort: 'low' }, highProviderConfiguration: { reasoningEffort: 'high' }, maxProviderConfiguration: { reasoningEffort: 'max' } }); expect(context.importedStates).toHaveLength(100); expect([...context.importedStates.values()][0]).toMatchObject({ status: ADAPTIVE_STATES.imported, semanticAttempts: { low: 0, high: 0, max: 0 }, usage: { low: {}, high: {}, max: {} } }) })
  it('still fails closed on inherited semantic identity drift', async () => { await expect(buildSemanticNPreflight({ target: 200, pipelineRoot: '/pipeline', ...(await fixture({ identityDrift: true })) })).rejects.toMatchObject({ code: 'PRIOR_IDENTITY_MISMATCH' }) })
  it('still fails closed on imported artifact drift', async () => { await expect(buildSemanticNPreflight({ target: 200, pipelineRoot: '/pipeline', ...(await fixture({ artifactDrift: true })) })).rejects.toMatchObject({ code: 'IMPORT_ARTIFACT_DRIFT' }) })
})
