import { describe, expect, it, vi } from 'vitest'
import { runScale500Production, SCALE_500_CADENCE } from './runScale500Production.mjs'

const completeSummary = (target) => ({ importedValid: target - 100, generatedValidThisRun: 100, pending: 0, providerFailures: 0, uncertain: 0, terminalSemanticFailures: 0 })
function harness({ acquisitionShortfallAt = null, semanticStopAt = null, uncertainAt = null, completed = new Set() } = {}) {
  const calls = []; const cohorts = new Set(completed)
  const acquisitionPreflight = vi.fn(async ({ targetReadyCount }) => ({ readyCount: targetReadyCount, targetMet: true, uncertainCount: uncertainAt === targetReadyCount + 100 ? 1 : 0 }))
  const acquire = vi.fn(async ({ targetReadyCount, maxFreshCandidates, maxHttpRequests }) => { calls.push(`acquire:${targetReadyCount + 100}`); return { readyCount: acquisitionShortfallAt === targetReadyCount + 100 ? targetReadyCount - 1 : targetReadyCount, targetMet: acquisitionShortfallAt !== targetReadyCount + 100, maxFreshCandidates, maxHttpRequests } })
  const semanticPreflight = vi.fn()
  const buildCohort = vi.fn(async ({ targetCount }) => { calls.push(`build:${targetCount}`); cohorts.add(targetCount) })
  const launchSemantic = vi.fn(async ([, target]) => { const n = Number(target); calls.push(`semantic:${n}`); const summary = semanticStopAt === n ? { ...completeSummary(n), pending: 1, generatedValidThisRun: 99 } : completeSummary(n); return { manifest: { states: {}, summary, currentRunHttpRequests: 0 } } })
  // summarizeAdaptiveBatch derives from states, so provide explicit state sets.
  launchSemantic.mockImplementation(async (argv) => { const n = Number(argv[1]); calls.push(`semantic:${n}`); const count = semanticStopAt === n ? 99 : 100; const states = {}; for (let i = 0; i < n - 100; i++) states[`i${i}`] = { status: 'IMPORTED_VALID' }; for (let i = 0; i < count; i++) states[`g${i}`] = { status: 'HIGH_VALID', usage: {} }; if (count < 100) states.pending = { status: 'PENDING_HIGH', usage: {} }; return { manifest: { states, currentRunHttpRequests: count } } })
  semanticPreflight.mockImplementation(async ({ target }) => { if (!cohorts.has(target)) { const error = new Error('missing'); error.code = 'REQUIRED_MANIFEST_MISSING'; throw error } const states = {}; if (completed.has(target)) { for (let i = 0; i < target - 100; i++) states[`i${i}`] = { status: 'IMPORTED_VALID' }; for (let i = 0; i < 100; i++) states[`g${i}`] = { status: 'HIGH_VALID', usage: {} } } return { preflight: { importedValid: target - 100, pendingFresh: completed.has(target) ? 0 : 100, generatedValidThisRun: completed.has(target) ? 100 : 0 }, manifest: completed.has(target) ? { states, currentRunHttpRequests: 0 } : null } })
  return { calls, acquisitionPreflight, acquire, semanticPreflight, buildCohort, launchSemantic }
}

describe('Scale-500 production orchestrator', () => {
  it('preflight makes no acquisition or semantic execution calls', async () => { const h = harness(); const result = await runScale500Production([], h); expect(result.executionAuthorized).toBe(false); expect(h.acquire).not.toHaveBeenCalled(); expect(h.launchSemantic).not.toHaveBeenCalled() })
  it('runs checkpoints in 200, 300, 400, 500 order with hard budgets', async () => { const h = harness(); const result = await runScale500Production(['--execute-authorized-scale-500-production'], { ...h, env: { TMDB_READ_ACCESS_TOKEN: 't', KIMI_API_KEY: 'k' } }); expect(result.status).toBe('COMPLETE'); expect(h.calls).toEqual(SCALE_500_CADENCE.flatMap((n) => [`build:${n}`, `semantic:${n}`])); for (const call of h.launchSemantic.mock.calls) expect(call[0]).toEqual(expect.arrayContaining(['--max-fresh-candidates', '100', '--max-http-requests', '125'])) })
  it('stops before semantic work on acquisition shortfall', async () => { const h = harness({ acquisitionShortfallAt: 200 }); h.acquisitionPreflight.mockResolvedValue({ readyCount: 0, targetMet: false, uncertainCount: 0 }); const result = await runScale500Production(['--execute-authorized-scale-500-production'], { ...h, env: { TMDB_READ_ACCESS_TOKEN: 't', KIMI_API_KEY: 'k' } }); expect(result.status).toBe('STOPPED_ACQUISITION_SHORTFALL'); expect(h.launchSemantic).not.toHaveBeenCalled() })
  it('stops on incomplete semantic checkpoint and gates the next stage', async () => { const h = harness({ semanticStopAt: 200 }); const result = await runScale500Production(['--execute-authorized-scale-500-production'], { ...h, env: { TMDB_READ_ACCESS_TOKEN: 't', KIMI_API_KEY: 'k' } }); expect(result.status).toBe('STOPPED_SEMANTIC_INCOMPLETE'); expect(h.calls).toEqual(['build:200', 'semantic:200']) })
  it('refuses ambiguous factual dispatch state', async () => { const h = harness({ uncertainAt: 200 }); await expect(runScale500Production(['--execute-authorized-scale-500-production'], { ...h, env: { TMDB_READ_ACCESS_TOKEN: 't', KIMI_API_KEY: 'k' } })).rejects.toMatchObject({ code: 'UNCERTAIN_ACQUISITION' }); expect(h.acquire).not.toHaveBeenCalled() })
  it('resume skips already complete stages', async () => { const h = harness({ completed: new Set([200, 300, 400, 500]) }); const result = await runScale500Production(['--execute-authorized-scale-500-production'], { ...h, env: { TMDB_READ_ACCESS_TOKEN: 't', KIMI_API_KEY: 'k' } }); expect(result.status).toBe('COMPLETE'); expect(h.acquire).not.toHaveBeenCalled(); expect(h.launchSemantic).not.toHaveBeenCalled() })
})
