import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

import { FINAL_CLOSURE_PATH, buildFinalClosure, PROMOTION_READINESS_PATH, validateFinalClosure, writeFinalClosure } from './t3FinalClosureReconciliation.mjs'

test('conserves normal population and preserves zero unresolved semantic branches', () => { const { closure, readiness } = buildFinalClosure(); assert.equal(validateFinalClosure({ closure, readiness }), true); assert.equal(closure.partitions.humanSemanticClosureAcceptedCandidateIds.length, 139); assert.equal(closure.partitions.terminalPreHumanExclusionCandidateIds.length, 2); assert.equal(closure.partitions.structuralQuarantineCandidateIds.length, 9) })
test('keeps deferred out of the denominator and promotion/runtime disabled', () => { const { closure, readiness } = buildFinalClosure(); assert.equal(closure.deferred.candidateIds[0], 'exp100-tmdb-1156593'); assert.equal(closure.promotionEligibleCandidateIds.length, 0); assert.equal(readiness.promotionReadiness, false); assert.equal(closure.promotionAuthorized, false); assert.equal(closure.runtimeAssemblyAuthorized, false) })
test('rejects invalid promotion readiness binding or population drift', () => { const { closure, readiness } = buildFinalClosure(); assert.throws(() => validateFinalClosure({ closure: { ...closure, counts: { ...closure.counts, accepted: 140 } }, readiness }), /COUNT_INVALID/); assert.throws(() => validateFinalClosure({ closure, readiness: { ...readiness, finalClosureHash: 'wrong' } }), /READINESS_INVALID/) })
test('persisted closure/readiness bindings are immutable and replay is rejected', () => { const read = (file) => JSON.parse(fs.readFileSync(file)); const closure = read(FINAL_CLOSURE_PATH); const readiness = read(PROMOTION_READINESS_PATH); assert.equal(validateFinalClosure({ closure, readiness }), true); assert.deepEqual(closure.partitions.terminalPreHumanExclusionCandidateIds, ['scale500-tmdb-12104', 'scale500-tmdb-26691']); assert.equal(closure.partitions.structuralQuarantineCandidateIds.length, 9); assert.deepEqual(closure.promotionEligibleCandidateIds, []); assert.throws(() => writeFinalClosure(), /REPLAY_REJECTED/) })
