import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { hashArtifact, hashBytes, serializeArtifactForPersistence } from './validatePromotionContract.mjs'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const ROOT = 'catalogue-pipeline/generated/catalogue-promotion/v8-2-scale-tranche-3'
const ASSET_ROOT = `${ROOT}/stage-2-poster-assets-v1`
export const AUTHORIZATION_PATH = `${ROOT}/t3-stage-2-palette-generation-authorization.v1.json`
export const MANIFEST_PATH = `${ROOT}/t3-stage-2-palette-generation-manifest.v1.json`
export const OUTPUT_ROOT = `${ROOT}/stage-2-palette-artifacts-v1`
const read = (root, p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'))
const rawHash = (root, p) => hashBytes(fs.readFileSync(path.join(root, p)))
const fail = (ok, code) => { if (!ok) throw new Error(code) }
function writeNew(root, p, value) { const target = path.join(root, p); fail(!fs.existsSync(target), 'T3_PALETTE_AUTHORIZATION_REPLAY_REJECTED'); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, serializeArtifactForPersistence(value), { flag: 'wx', mode: 0o600 }) }

export function buildPaletteGenerationGovernance({ repoRoot = REPO } = {}) {
  const paths = { posterAuthorization: `${ROOT}/t3-stage-2-poster-acquisition-authorization.v1.json`, posterExecutionAuthorization: `${ROOT}/t3-stage-2-poster-acquisition-execution-authorization.v1.json`, posterCompletion: `${ASSET_ROOT}/t3-stage-2-poster-acquisition-completion-manifest.v1.json`, posterLedger: `${ASSET_ROOT}/t3-stage-2-poster-acquisition-execution-ledger.v1.json`, stage2FailureReconciliation: `${ROOT}/t3-stage-2-assembly-failure-reconciliation.v1.json`, stage2Authorization: `${ROOT}/t3-stage-2-production-assembly-dry-run-authorization.v1.json`, paletteAlgorithm: 'catalogue-pipeline/scripts/paletteAlgorithmV11.mjs', paletteValidator: 'catalogue-pipeline/scripts/validatePromotionContract.mjs', productionSchema: 'catalogue-pipeline/schemas/production-record.v2.schema.json', t2AssemblyReference: 'catalogue-pipeline/scripts/scaleTranche2ProductionAssembly.mjs' }
  const posterAuthorization = read(repoRoot, paths.posterAuthorization); const posterCompletion = read(repoRoot, paths.posterCompletion); const posterLedger = read(repoRoot, paths.posterLedger); const stage2 = read(repoRoot, paths.stage2Authorization)
  fail(posterAuthorization.acquisitionPopulation === 139 && posterCompletion.status === 'COMPLETE_ALL_ACQUIRED' && posterCompletion.population === 139 && posterCompletion.acquiredCandidateIds.length === 139 && posterCompletion.failedCandidateIds.length === 0 && posterLedger.acquired === 139 && posterLedger.failed === 0 && posterLedger.palettesGenerated === 0, 'T3_PALETTE_AUTH_ADMISSION_INVALID')
  fail(hashArtifact(posterCompletion) === posterLedger.completionManifestHash && posterCompletion.executionAuthorizationHash === hashArtifact(read(repoRoot, paths.posterExecutionAuthorization)) && stage2.candidateIds.length === 139 && stage2.candidateIdsHash === hashArtifact(stage2.candidateIds), 'T3_PALETTE_AUTH_BINDING_INVALID')
  const records = posterCompletion.records.map((record) => {
    const resultPath = `${ASSET_ROOT}/assets/${record.candidateId}/result.json`; const posterPath = `${ASSET_ROOT}/assets/${record.candidateId}/poster`; const result = read(repoRoot, resultPath); const bytes = fs.readFileSync(path.join(repoRoot, posterPath))
    fail(record.status === 'POSTER_ASSET_ACQUIRED' && result.status === 'POSTER_ASSET_ACQUIRED' && record.posterPath === result.posterPath && record.posterByteHash === result.posterByteHash && hashBytes(bytes) === record.posterByteHash && record.localAssetPath === posterPath, 'T3_PALETTE_AUTH_POSTER_BINDING_INVALID')
    return { candidateId: record.candidateId, tmdbId: record.tmdbId, posterPath: record.posterPath, posterAssetPath: posterPath, sourcePosterHash: record.posterByteHash, posterAcquisitionResultPath: resultPath, posterAcquisitionResultHash: hashArtifact(result) }
  })
  fail(records.length === 139 && new Set(records.map((r) => r.candidateId)).size === 139 && records.every((r) => /^[a-z0-9-]+$/.test(r.candidateId)), 'T3_PALETTE_AUTH_POPULATION_INVALID')
  const bindings = Object.fromEntries(Object.entries(paths).map(([name, p]) => [name, { path: p, rawFileHash: rawHash(repoRoot, p), ...(p.endsWith('.json') ? { canonicalArtifactHash: hashArtifact(read(repoRoot, p)) } : {}) }]))
  const authorization = { schemaVersion: 't3-stage-2-palette-generation-authorization.v1', status: 'T3_PALETTE_GENERATION_AUTHORIZED_AWAITING_EXECUTION_AUTHORIZATION', trancheId: 'SCALE_TRANCHE_3', bindings, palettePopulation: 139, candidateIds: records.map((r) => r.candidateId), candidateIdsHash: hashArtifact(records.map((r) => r.candidateId)), paletteAlgorithm: { path: paths.paletteAlgorithm, rawFileHash: bindings.paletteAlgorithm.rawFileHash, algorithmVersion: 'palette-algorithm.v1.1', function: 'paletteFromPosterV11' }, paletteArtifactContract: { schemaVersion: 'palette-artifact.v1', validatorPath: paths.paletteValidator, validatorRawFileHash: bindings.paletteValidator.rawFileHash, method: 'poster-algorithm', requiredBindings: ['candidateId', 'tmdbId', 'palette', 'sourcePosterIdentity.posterPath', 'sourcePosterHash', 'algorithmVersion'] }, outputPolicy: { outputRoot: OUTPUT_ROOT, generated: true, t3Scoped: true, runtimeWriteAllowed: false, promotionAllowed: false }, semanticMutationAllowed: false, networkCallsAuthorized: 0, externalProviderCallsAuthorized: 0, paletteFailurePolicy: { states: ['PALETTE_GENERATED', 'PALETTE_GENERATION_FAILED'], semanticStatusUnchanged: true, noPosterSubstitution: true, noFallbackPalette: true, stage2RerunRequiresNewAuthorization: true }, cachePolicy: { reuseOnlyIfCandidatePosterHashAndAlgorithmHashMatch: true, conflictingArtifact: 'REJECT_FAIL_CLOSED', overwriteConflictingArtifact: false, completedReplay: 'REJECT_OR_EXPLICIT_VALIDATED_NO_OP_ONLY' }, determinismRequirement: { secondPassRequired: true, paletteValuesEqual: true, canonicalArtifactHashStable: true }, productionRecordMapping: { curatedMovieField: 'curatedMovie.palette', provenanceField: 'provenance.paletteArtifactHash', artifactSourceField: 'paletteArtifact.sourcePosterHash' }, futureExecutor: { executorAuthorized: false, requiredBindings: ['palette authorization hash', 'poster completion hash', 'poster ledger hash', '139 candidate/sourcePosterHash set', 'algorithm hash', 'validator hash', 'output policy'], networkAllowed: false, providerCallsAllowed: 0, runtimeWriteAllowed: false, promotionAllowed: false }, providerAccounting: { physicalGeminiCalls: 151, hardPhysicalCap: 180, remainingHeadroom: 29 }, palettesGenerated: 0, postersChanged: false, stage2Reruns: 0 }
  const manifest = { schemaVersion: 't3-stage-2-palette-generation-manifest.v1', status: 'FROZEN_AWAITING_EXECUTION_AUTHORIZATION', authorizationHash: hashArtifact(authorization), population: 139, records, outputRoot: OUTPUT_ROOT, paletteGenerationExecuted: false, networkCallsMade: 0, providerCallsMade: 0 }
  return { authorization, manifest }
}
export function validatePaletteGenerationGovernance({ authorization, manifest }) {
  fail(authorization?.schemaVersion === 't3-stage-2-palette-generation-authorization.v1' && authorization.palettePopulation === 139 && authorization.candidateIds.length === 139 && authorization.candidateIdsHash === hashArtifact(authorization.candidateIds), 'T3_PALETTE_AUTH_SCHEMA_INVALID')
  fail(authorization.paletteAlgorithm.algorithmVersion === 'palette-algorithm.v1.1' && /^sha256:[0-9a-f]{64}$/.test(authorization.paletteAlgorithm.rawFileHash) && authorization.paletteArtifactContract.schemaVersion === 'palette-artifact.v1' && authorization.outputPolicy.outputRoot === OUTPUT_ROOT, 'T3_PALETTE_AUTH_CONTRACT_INVALID')
  fail(authorization.semanticMutationAllowed === false && authorization.networkCallsAuthorized === 0 && authorization.externalProviderCallsAuthorized === 0 && authorization.outputPolicy.runtimeWriteAllowed === false && authorization.outputPolicy.promotionAllowed === false && authorization.futureExecutor.executorAuthorized === false && authorization.palettesGenerated === 0, 'T3_PALETTE_AUTH_GUARD_INVALID')
  fail(authorization.determinismRequirement.secondPassRequired === true && authorization.cachePolicy.conflictingArtifact === 'REJECT_FAIL_CLOSED' && manifest?.authorizationHash === hashArtifact(authorization) && manifest.records.length === 139 && manifest.records.every((r) => /^sha256:[0-9a-f]{64}$/.test(r.sourcePosterHash)), 'T3_PALETTE_AUTH_MANIFEST_INVALID')
  return true
}
export function writePaletteGenerationGovernance({ repoRoot = REPO } = {}) { const value = buildPaletteGenerationGovernance({ repoRoot }); validatePaletteGenerationGovernance(value); writeNew(repoRoot, AUTHORIZATION_PATH, value.authorization); writeNew(repoRoot, MANIFEST_PATH, value.manifest); return { authorizationHash: hashArtifact(value.authorization), manifestHash: hashArtifact(value.manifest) } }
if (import.meta.url === `file://${process.argv[1]}`) console.log(JSON.stringify(writePaletteGenerationGovernance(), null, 2))
